In [1]:
import pandas as pd

In [31]:
city_2018 =  pd.read_csv('/Users/utilisateur/Documents/Le_Wagon/Resilience/cdp-unlocking-climate-solutions/Cities/Cities Responses/2018_Full_Cities_Dataset.csv')

In [3]:
city_2018

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update
0,CDP Cities 2018,2018,3203,City of Chicago,United States of America,North America,Water,Wastewater,16.1,Please provide the percentage breakdown of the...,1,Percentage of wastewater collected,5,Other type of wastewater,NaN,NaN,NaN,24/06/2020 05:28:18 AM
1,CDP Cities 2018,2018,50555,City of Hamilton,Canada,North America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,5,Probability of hazard,4,NaN,Medium High,NaN,NaN,24/06/2020 05:28:18 AM
2,CDP Cities 2018,2018,50392,Prefeitura de Vitória,Brazil,Latin America,Emissions Reduction: City-wide,Emissions Reduction Actions : City-wide,8.4,What actions is your city taking to reduce emi...,1,Emissions reduction project activity,3,NaN,On-site renewable energy generation,NaN,NaN,24/06/2020 05:28:18 AM
3,CDP Cities 2018,2018,36522,Comune di Verbania,Italy,Europe,Strategy,Energy,9.0,Please indicate the energy mix of electricity ...,2,Gas,1,Energy consumption percentage,NaN,NaN,NaN,24/06/2020 05:28:18 AM
4,CDP Cities 2018,2018,35873,Municipality of Medellín,Colombia,Latin America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,3,Magnitude of impact,6,NaN,Serious,NaN,NaN,24/06/2020 05:28:18 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186829,CDP Cities 2018,2018,74594,City of Boynton Beach,United States of America,North America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,6,Consequence of hazard,2,NaN,High,NaN,NaN,24/06/2020 05:28:18 AM
186830,CDP Cities 2018,2018,60602,"Town of Ajax, ON",Canada,North America,Hazards and Adaptation,Climate Hazards,2.0b,Please attach and provide details on your clim...,6,Primary author of assessment,2,NaN,Regional / state / provincial government,NaN,NaN,24/06/2020 05:28:18 AM
186831,CDP Cities 2018,2018,49334,"City of Richmond, VA",United States of America,North America,Hazards and Adaptation,Climate Hazards,2.3,Do you consider that the effects of climate ch...,1,Response,1,Please explain,Yes – business in my city will be negatively i...,NaN,NaN,24/06/2020 05:28:18 AM
186832,CDP Cities 2018,2018,31108,City of Houston,United States of America,North America,Strategy,Waste,14.3,How much organic waste does your city generate...,1,Amount of organic waste (tonnes per person per...,1,Total,24670.62,The total tons of organics collected for compo...,NaN,24/06/2020 05:28:18 AM
186833,CDP Cities 2018,2018,35858,City of Cape Town,South Africa,Africa,Strategy,Emissions Reduction: City-wide,8.3c,Please provide details of your total city-wide...,6,Estimated business as usual absolute emissions...,2,NaN,32811632,NaN,NaN,24/06/2020 05:28:18 AM

In [4]:
city_2018['Question Name'].nunique()

167

In [174]:
city_2018['Question Number'].unique()

array(['16.1', '2.2a', '8.4', '9.0', '7.13a', '7.11', '11.4', '1.2',
       '7.3a', '2.0c', '9.3', '6.5', '9.2a', '0.5', '2.4',
       'Response Language', '5.1a', '8.0b', '15.3a', '2.0b', '0.8', '6.6',
       '5.2', '2.0', '3.3', '10.9', '0.6', '0.3', '4.0a', '7.13', '7.0',
       '14.0', '7.2', '8.2b', '8.0a', '2.3', '3.1a', '0.1', '3.4', '6.1',
       '15.4', '5.1', '11.0', '15.3', '7.10', '7.5', '8.1', '8.2c', '3.6',
       '14.1', '7.7', '2.2', '1.4', '8.3', '1.4a', '6.8b', '5.5', '3.1',
       '3.9', '0.4', '3.7', '14.6', '6.8a', '6.0', '0.7', '8.3a', '7.8',
       '9.1', '9.2b', '1.3', '2.1a', '5.3', '7.12b', '3.8', '7.6a',
       '2.0a', '14.3', '6.9', '6.7', '6.10a', '1.1', '7.1', '8.3b',
       '9.3a', '5.4', '11.2', '10.7', '5.0', '3.2a', '3.0a', '5.8',
       '8.2a', '13.1', '9.2', '14.4', '15.0', '6.4', '7.4a', '11.5',
       '5.0a', '6.8', '15.3b', '14.5', '4.0', '10.8', '15.2', '0.2',
       '7.3', '1.8', '6.3', '8.3c', '7.12', '7.4b', '6.2', '5.7', '8.3d',
       '10.5', '7.12a', '1.0', '8.2', '10.0', '12.1', '6.10', '15.1',
       '7.6c', '2.1', '5.10', '3.0', '14.2', '3.1b', '3.5', '1.7', '12.0',
       '7.6d', '11.6', '16.3', '10.2', '1.10', '3.2', '6.10b', '10.6',
       '4.0b', '8.0', '1.5', '16.2', '7.10a', '11.3', '10.3', '5.9',
       '16.0', '7.6b', '7.9', '1.9', '10.1', '10.4', '16.3a', '7.4',
       '1.12', '9.0a', '5.6', '2.2b', '13.0', '11.1', '7.9a', '11.6a',
       '5.0b', '1.11', '1.6', '7.9b'], dtype=object)

In [6]:
city_2018['Section'].nunique()

37

In [7]:
city_2018['Parent Section'].nunique()

15

In [8]:
city_2018['Parent Section'].unique()

array(['Water', 'Climate Hazards', 'Emissions Reduction: City-wide',
       'Strategy', 'City Wide Emissions',
       'Governance and Data Management', 'Hazards and Adaptation',
       'Energy Data', 'Introduction', nan, 'Opportunities', 'Adaptation',
       'Local Government Emissions',
       'Emissions Reduction: Local Government', 'GHG Emissions Data',
       'Local Government Operations GHG Emissions Data'], dtype=object)

In [138]:
city_2018.groupby(['Question Number']).agg('Response Answer').unique()

Question Number
0.1                  [City / Municipality, Lorena é um município br...
0.2                                                              [nan]
0.3                  [Henriette Reker, 2019, Ron Christie, 2018, 20...
0.4                  [USD US Dollar, AUD Australian Dollar, DKK Dan...
0.5                  [2018-12-31, 2510737944000, nan, 2018-01-01, 2...
                                           ...
9.2a                 [2016, Other: All energy consumed(in TOE), The...
9.2b                 [Target is under development / consideration, ...
9.3                           [No, In progress, nan, Yes, Do not know]
9.3a                 [In accordance with the relevant provisions of...
Response Language    [Spanish, English, Portuguese, French, Japanes...
Name: Response Answer, Length: 169, dtype: object

In [10]:
city_2018[city_2018['Question Number']=='0.2']['Response Answer'].isnull().sum()

370

In [11]:
introduction = city_2018['Question Number'].filter(regex='^0.')

In [12]:
introduction

Series([], Name: Question Number, dtype: object)

In [13]:
city_2018['Question Number'].str.startswith(('O.'))

0         False
1         False
2         False
3         False
4         False
          ...
186829    False
186830    False
186831    False
186832    False
186833    False
Name: Question Number, Length: 186834, dtype: bool

In [14]:
city_2018.dtypes

Questionnaire           object
Year Reported to CDP     int64
Account Number           int64
Organization            object
Country                 object
CDP Region              object
Parent Section          object
Section                 object
Question Number         object
Question Name           object
Column Number            int64
Column Name             object
Row Number               int64
Row Name                object
Response Answer         object
Comments                object
File Name               object
Last update             object
dtype: object

In [15]:
import re

In [16]:
introduction = ['0.1', '0.2', '0.3']

In [17]:
(city_2018['Question Number'].str.startswith(f'{0}.')).sum()

11194

In [18]:
city_2018['Question Number'].shape

(186834,)

In [19]:
city_2018.loc[city_2018['Question Number'].str.startswith(f'{0}.')]['Question Number'].unique()

array(['0.5', '0.8', '0.6', '0.3', '0.1', '0.4', '0.7', '0.2'],
      dtype=object)

In [20]:
introduction = city_2018.loc[city_2018['Question Number'].str.startswith(f'{0}.')]['Question Number'].unique()
governance = city_2018.loc[city_2018['Question Number'].str.startswith(f'{1}.')]['Question Number'].unique()
climate_hazards = city_2018.loc[city_2018['Question Number'].str.startswith(f'{2}.')]['Question Number'].unique()

In [21]:
adaptation = city_2018.loc[city_2018['Question Number'].str.startswith(f'{3}.')]['Question Number'].unique()
social_risks = city_2018.loc[city_2018['Question Number'].str.startswith(f'{4}.')]['Question Number'].unique()
opportunities = city_2018.loc[city_2018['Question Number'].str.startswith(f'{5}.')]['Question Number'].unique()
#boundary_scope = city_2018.loc[city_2018['Question Number'].str.startswith(f'{6}.')]['Question Number'].unique()

In [22]:
boundary = ['6.0', '6.1', '6.2', '6.3', '6.4']
energy_data = ['6.5', '6.6']
ghg_emissions = ['6.7','6.8','6.8a','6.8b','6.9']
ext_verification = ['6.10','6.10a', '6.10b']

In [211]:
city_wide_emissions = city_2018.loc[city_2018['Question Number'].str.startswith(f'{7}.')]['Question Number'].unique()
strategy_ghg = ['8.0','8.0a', '8.0b', '8.1']
strategy_emissions_reduction = ['8.2','8.2a','8.2b','8.2c','8.3', '8.3a', '8.3b','8.3c','8.3d','8.4']
energy = city_2018.loc[city_2018['Question Number'].str.startswith(f'{9}.')]['Question Number'].unique()

In [212]:
transport = city_2018.loc[city_2018['Question Number'].str.startswith(f'{11}.')]['Question Number'].unique()
water_supply = city_2018.loc[city_2018['Question Number'].str.startswith(f'{15}.')]['Question Number'].unique()
language = city_2018.loc[city_2018['Question Number'].str.startswith('Respo')]['Question Number'].unique()

In [213]:
waste_water= city_2018.loc[city_2018['Question Number'].str.startswith(f'{16}.')]['Question Number'].unique()
waste_strat= city_2018.loc[city_2018['Question Number'].str.startswith(f'{14}.')]['Question Number'].unique()
food_strat = city_2018.loc[city_2018['Question Number'].str.startswith(f'{13}.')]['Question Number'].unique()
urban_planning = city_2018.loc[city_2018['Question Number'].str.startswith(f'{12}.')]['Question Number'].unique()
building_strat = city_2018.loc[city_2018['Question Number'].str.startswith(f'{10}.')]['Question Number'].unique()

In [220]:
a = ['16.1', '2.2a', '8.4', '9.0', '7.13a', '7.11', '11.4', '1.2',
       '7.3a', '2.0c', '9.3', '6.5', '9.2a', '0.5', '2.4',
       'Response Language', '5.1a', '8.0b', '15.3a', '2.0b', '0.8', '6.6',
       '5.2', '2.0', '3.3', '10.9', '0.6', '0.3', '4.0a', '7.13', '7.0',
       '14.0', '7.2', '8.2b', '8.0a', '2.3', '3.1a', '0.1', '3.4', '6.1',
       '15.4', '5.1', '11.0', '15.3', '7.10', '7.5', '8.1', '8.2c', '3.6',
       '14.1', '7.7', '2.2', '1.4', '8.3', '1.4a', '6.8b', '5.5', '3.1',
       '3.9', '0.4', '3.7', '14.6', '6.8a', '6.0', '0.7', '8.3a', '7.8',
       '9.1', '9.2b', '1.3', '2.1a', '5.3', '7.12b', '3.8', '7.6a',
       '2.0a', '14.3', '6.9', '6.7', '6.10a', '1.1', '7.1', '8.3b',
       '9.3a', '5.4', '11.2', '10.7', '5.0', '3.2a', '3.0a', '5.8',
       '8.2a', '13.1', '9.2', '14.4', '15.0', '6.4', '7.4a', '11.5',
       '5.0a', '6.8', '15.3b', '14.5', '4.0', '10.8', '15.2', '0.2',
       '7.3', '1.8', '6.3', '8.3c', '7.12', '7.4b', '6.2', '5.7', '8.3d',
       '10.5', '7.12a', '1.0', '8.2', '10.0', '12.1', '6.10', '15.1',
       '7.6c', '2.1', '5.10', '3.0', '14.2', '3.1b', '3.5', '1.7', '12.0',
       '7.6d', '11.6', '16.3', '10.2', '1.10', '3.2', '6.10b', '10.6',
       '4.0b', '8.0', '1.5', '16.2', '7.10a', '11.3', '10.3', '5.9',
       '16.0', '7.6b', '7.9', '1.9', '10.1', '10.4', '16.3a', '7.4',
       '1.12', '9.0a', '5.6', '2.2b', '13.0', '11.1', '7.9a', '11.6a',
       '5.0b', '1.11', '1.6', '7.9b']

In [221]:
city_wide_emissions

array(['7.13a', '7.11', '7.3a', '7.13', '7.0', '7.2', '7.10', '7.5',
       '7.7', '7.8', '7.12b', '7.6a', '7.1', '7.4a', '7.3', '7.12',
       '7.4b', '7.12a', '7.6c', '7.6d', '7.10a', '7.6b', '7.9', '7.4',
       '7.9a', '7.9b'], dtype=object)

In [222]:
list_sectors = ['introduction','governance','climate_hazards','adaptation','social_risks','opportunities','boundary','energy_data',
               'ghg_emissions','ext_verification','city_wide_emissions','strategy_ghg','strategy_emissions_reduction','energy',
               'transport', 'water_supply', 'language', 'waste_water', 'waste_strat', 'food_strat', 'urban_planning', 'building_strat']

In [223]:
list_sect = [introduction, governance , climate_hazards,adaptation,social_risks,opportunities,boundary,energy_data,
               ghg_emissions,ext_verification,city_wide_emissions,strategy_ghg,strategy_emissions_reduction,energy,
               transport, water_supply, language, waste_water, waste_strat, food_strat, urban_planning, building_strat]

In [226]:
w=0
z = []
for i in range(len(list_sect)):
    w = w+ len(list_sect[i])
    for j in range(len(list_sect[i])):
        z.append(list_sect[i][j])

In [227]:
for i in range(len(a)):
    if a[i] in z:
        print('ok')
    else:
        print(a[i])

ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok

In [192]:
for i in range(len(z)):
    for y in range(len(a)):
        if a[y] in z[i]

[array(['0.5', '0.8', '0.6', '0.3', '0.1', '0.4', '0.7', '0.2'],
       dtype=object),
 array(['1.2', '1.4', '1.4a', '1.3', '1.1', '1.8', '1.0', '1.7', '1.10',
        '1.5', '1.9', '1.12', '1.11', '1.6'], dtype=object),
 array(['2.2a', '2.0c', '2.4', '2.0b', '2.0', '2.3', '2.2', '2.1a', '2.0a',
        '2.1', '2.2b'], dtype=object),
 array(['3.3', '3.1a', '3.4', '3.6', '3.1', '3.9', '3.7', '3.8', '3.2a',
        '3.0a', '3.0', '3.1b', '3.5', '3.2'], dtype=object),
 array(['4.0a', '4.0', '4.0b'], dtype=object),
 array(['5.1a', '5.2', '5.1', '5.5', '5.3', '5.4', '5.0', '5.8', '5.0a',
        '5.7', '5.10', '5.9', '5.6', '5.0b'], dtype=object),
 ['6.0', '6.1', '6.2', '6.3', '6.4'],
 ['6.5', '6.6'],
 ['6.7', '6.8', '6.8a', '6.8b', '6.9'],
 ['6.10', '6.10a', '6.10b'],
 array(['7.13a', '7.11', '7.3a', '7.13', '7.0', '7.2', '7.10', '7.5',
        '7.7', '7.8', '7.12b', '7.6a', '7.1', '7.4a', '7.3', '7.12',
        '7.4b', '7.12a', '7.6c', '7.6d', '7.10a', '7.6b', '7.9', '7.4',
        '7.9a', '7.9b'], dtype=object),
 ['8.0', '8.0a', '8.0b', '8.1'],
 ['8.2', '8.2a', '8.2c', '8.3', '8.3a', '8.3b', '8.3c', '8.3d', '8.4'],
 array(['9.0', '9.3', '9.2a', '9.1', '9.2b', '9.3a', '9.2', '9.0a'],
       dtype=object),
 array(['11.4', '11.0', '11.2', '11.5', '11.6', '11.3', '11.1', '11.6a'],
       dtype=object),
 array(['15.3a', '15.4', '15.3', '15.0', '15.3b', '15.2', '15.1'],
       dtype=object),
 array(['Response Language'], dtype=object),
 array(['16.1', '16.3', '16.2', '16.0', '16.3a'], dtype=object),
 array(['14.0', '14.1', '14.6', '14.3', '14.4', '14.5', '14.2'],
       dtype=object),
 array(['13.1', '13.0'], dtype=object),
 array(['12.1', '12.0'], dtype=object),
 array(['10.9', '10.7', '10.8', '10.5', '10.0', '10.2', '10.6', '10.3',
        '10.1', '10.4'], dtype=object)]

city_2018['New Section']=city_2018['Question Number'].apply(lambda x:'introduction' if x in introduction else 'NaN')

for i in range(0,len(list_sectors)-1):
    city_2018['New Section']=city_2018['Question Number'].apply(lambda x: f'{list_sectors[i]}' if x in list_sect[i] else pass)

In [ ]:
city_2018.shape[0]

In [228]:
new_section_list = []
for y in range(city_2018.shape[0]):
    for i in range(0,len(list_sectors)):
        if city_2018['Question Number'][y] in list_sect[i]:
            new_section_list.append(f'{list_sectors[i]}')

In [229]:
city_2018['SectionN'] = new_section_list

In [232]:
city_2018

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update,SectionN
0,CDP Cities 2018,2018,3203,City of Chicago,United States of America,North America,Water,Wastewater,16.1,Please provide the percentage breakdown of the...,1,Percentage of wastewater collected,5,Other type of wastewater,NaN,NaN,NaN,24/06/2020 05:28:18 AM,waste_water
1,CDP Cities 2018,2018,50555,City of Hamilton,Canada,North America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,5,Probability of hazard,4,NaN,Medium High,NaN,NaN,24/06/2020 05:28:18 AM,climate_hazards
2,CDP Cities 2018,2018,50392,Prefeitura de Vitória,Brazil,Latin America,Emissions Reduction: City-wide,Emissions Reduction Actions : City-wide,8.4,What actions is your city taking to reduce emi...,1,Emissions reduction project activity,3,NaN,On-site renewable energy generation,NaN,NaN,24/06/2020 05:28:18 AM,strategy_emissions_reduction
3,CDP Cities 2018,2018,36522,Comune di Verbania,Italy,Europe,Strategy,Energy,9.0,Please indicate the energy mix of electricity ...,2,Gas,1,Energy consumption percentage,NaN,NaN,NaN,24/06/2020 05:28:18 AM,energy
4,CDP Cities 2018,2018,35873,Municipality of Medellín,Colombia,Latin America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,3,Magnitude of impact,6,NaN,Serious,NaN,NaN,24/06/2020 05:28:18 AM,climate_hazards
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186829,CDP Cities 2018,2018,74594,City of Boynton Beach,United States of America,North America,Climate Hazards,Climate Hazards,2.2a,Please list the most significant climate hazar...,6,Consequence of hazard,2,NaN,High,NaN,NaN,24/06/2020 05:28:18 AM,climate_hazards
186830,CDP Cities 2018,2018,60602,"Town of Ajax, ON",Canada,North America,Hazards and Adaptation,Climate Hazards,2.0b,Please attach and provide details on your clim...,6,Primary author of assessment,2,NaN,Regional / state / provincial government,NaN,NaN,24/06/2020 05:28:18 AM,climate_hazards
186831,CDP Cities 2018,2018,49334,"City of Richmond, VA",United States of America,North America,Hazards and Adaptation,Climate Hazards,2.3,Do you consider that the effects of climate ch...,1,Response,1,Please explain,Yes – business in my city will be negatively i...,NaN,NaN,24/06/2020 05:28:18 AM,climate_hazards
186832,CDP Cities 2018,2018,31108,City of Houston,United States of America,North America,Strategy,Waste,14.3,How much organic waste does your city generate...,1,Amount of organic waste (tonnes per person per...,1,Total,24670.62,The total tons of organics collected for compo...,NaN,24/06/2020 05:28:18 AM,waste_strat
186833,CDP Cities 2018,2018,35858,City of Cape Town,South Africa,Africa,Strategy,Emissions Reduction: City-wide,8.3c,Please provide details of your total city-wide...,6,Estimated business as usual absolute emissions...,2,NaN,32811632,NaN,NaN,24/06/2020 05:28:18 AM,strategy_emissions_reduction

In [ ]:
city_2018

In [40]:
import numpy as np

In [56]:
w=0
for i in np.unique(new_section_list):
    print(i, new_section_list.count(i))
    w += new_section_list.count(i)
print(w)

adaptation 16974
boundary 2282
city_wide_emissions 12394
climate_hazards 33805
energy 11335
energy_data 6224
ext_verification 704
ghg_emissions 2640
governance 6790
introduction 11194
opportunities 12454
social_risks 3435
strategy_emissions_reduction 17195
strategy_ghg 11396
transport 20124
168946

In [195]:
city_2018.loc[city_2018['Question Number'].str.startswith(f'{6}.')]['Question Name'].nunique()

15

In [304]:
city_2018.loc[city_2018['Question Number'].str.startswith(f'{12}.{1}')]['Response Answer'].value_counts(normalize=True, dropna=False) * 100

NaN     51.428571
100     15.714286
90       4.285714
89       2.857143
92       2.857143
99       2.857143
20       2.857143
75       2.857143
80       1.428571
96.7     1.428571
96       1.428571
68       1.428571
72       1.428571
95       1.428571
83       1.428571
94       1.428571
45       1.428571
77       1.428571
Name: Response Answer, dtype: float64

In [297]:
city_2018.loc[city_2018['Question Number']==f'{14}.{6}a']['Response Answer'].value_counts(normalize=True, dropna=False) * 100

Series([], Name: Response Answer, dtype: float64)

In [298]:
city_2018.loc[city_2018['Question Number'].str.startswith(f'{14}.{6}')]['Question Name'].unique()

array(['Please provide details of your city’s landfill gas:'],
      dtype=object)

In [252]:
city_2018.loc[city_2018['Question Number'].str.startswith(f'{14}.{6}')]

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update,SectionN
143,CDP Cities 2018,2018,54291,Chengdu Municipal Government,China,East Asia,Strategy,Waste,14.6,Please provide details of your city’s landfill...,1,Percentage of landfill gas collected,1,Please complete,NaN,NaN,NaN,24/06/2020 05:28:18 AM,waste_strat
148,CDP Cities 2018,2018,14874,"City of Portland, OR",United States of America,North America,Strategy,Waste,14.6,Please provide details of your city’s landfill...,2,Percentage of landfill gas utilized,1,Please complete,NaN,NaN,NaN,24/06/2020 05:28:18 AM,waste_strat
184,CDP Cities 2018,2018,35904,Kolkata Metropolitan Area,India,South and West Asia,Strategy,Waste,14.6,Please provide details of your city’s landfill...,2,Percentage of landfill gas utilized,1,Please complete,NaN,NaN,NaN,24/06/2020 05:28:18 AM,waste_strat
670,CDP Cities 2018,2018,1184,City of Austin,United States of America,North America,Strategy,Waste,14.6,Please provide details of your city’s landfill...,1,Percentage of landfill gas collected,1,Please complete,NaN,NaN,NaN,24/06/2020 05:28:18 AM,waste_strat
4118,CDP Cities 2018,2018,31150,Bangkok Metropolitan Administration,Thailand,Southeast Asia and Oceania,Strategy,Waste,14.6,Please provide details of your city’s landfill...,1,Percentage of landfill gas collected,1,Please complete,10,NaN,NaN,24/06/2020 05:28:18 AM,waste_strat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183402,CDP Cities 2018,2018,14088,City of Oslo,Norway,Europe,Strategy,Waste,14.6,Please provide details of your city’s landfill...,1,Percentage of landfill gas collected,1,Please complete,63,NaN,NaN,24/06/2020 05:28:18 AM,waste_strat
184080,CDP Cities 2018,2018,16581,City of Seattle,United States of America,North America,Strategy,Waste,14.6,Please provide details of your city’s landfill...,2,Percentage of landfill gas utilized,1,Please complete,NaN,Seattle's waste is disposed in the Columbia Ri...,NaN,24/06/2020 05:28:18 AM,waste_strat
184318,CDP Cities 2018,2018,31154,Bogotá Distrito Capital,Colombia,Latin America,Strategy,Waste,14.6,Please provide details of your city’s landfill...,2,Percentage of landfill gas utilized,1,Please complete,NaN,NaN,NaN,24/06/2020 05:28:18 AM,waste_strat
185262,CDP Cities 2018,2018,35873,Municipality of Medellín,Colombia,Latin America,Strategy,Waste,14.6,Please provide details of your city’s landfill...,1,Percentage of landfill gas collected,1,Please complete,NaN,NaN,NaN,24/06/2020 05:28:18 AM,waste_strat
185796,CDP Cities 2018,2018,31009,City of Copenhagen,Denmark,Europe,Strategy,Waste,14.6,Please provide details of your city’s landfill...,1,Percentage of landfill gas collected,1,Please complete,NaN,NaN,NaN,24/06/2020 05:28:18 AM,waste_strat

In [165]:
city_2018.loc[city_2018['Question Number'].str.startswith(f'{11}.{1}')]['Question Name'].unique()

array(['What is the total distance travelled by all transport modes annually in your city (kms)?'],
      dtype=object)

In [104]:
city_2018.loc[city_2018['Question Name'].str.startswith('Are you processing')]

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update
3101,CDP Cities 2018,2018,31175,City of Paris,France,Europe,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for vehicle fuel",NaN,NaN,24/06/2020 05:28:18 AM
5197,CDP Cities 2018,2018,35858,City of Cape Town,South Africa,Africa,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,No,However current project to install thermal hyd...,NaN,24/06/2020 05:28:18 AM
15694,CDP Cities 2018,2018,31185,City of Warsaw,Poland,Europe,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
21505,CDP Cities 2018,2018,35268,City of Boston,United States of America,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
23365,CDP Cities 2018,2018,31176,Prefeitura do Rio de Janeiro,Brazil,Latin America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
24643,CDP Cities 2018,2018,31117,City of Toronto,Canada,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
26724,CDP Cities 2018,2018,35885,Tel Aviv-Yafo Municipality,Israel,Middle East,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
31440,CDP Cities 2018,2018,3203,City of Chicago,United States of America,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
40266,CDP Cities 2018,2018,31149,City of Athens,Greece,Europe,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
43130,CDP Cities 2018,2018,31180,Región Metropolitana de Santiago,Chile,Latin America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",The city has more than one water treatment pla...,NaN,24/06/2020 05:28:18 AM
46033,CDP Cities 2018,2018,31181,City of Philadelphia,United States of America,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
62110,CDP Cities 2018,2018,31182,City of San Francisco,United States of America,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
69180,CDP Cities 2018,2018,54337,Greater Amman Municipality,Jordan,Middle East,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
70597,CDP Cities 2018,2018,31187,Seoul Metropolitan Government,Republic of Korea,East Asia,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
72210,CDP Cities 2018,2018,31165,Stadt Heidelberg,Germany,Europe,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
75729,CDP Cities 2018,2018,31090,District of Columbia,United States of America,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
76840,CDP Cities 2018,2018,20113,City of Vancouver,Canada,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, other: Heat/electricity powers treatment ...",NaN,NaN,24/06/2020 05:28:18 AM
81484,CDP Cities 2018,2018,3422,Greater London Authority,United Kingdom of Great Britain and Northern I...,Europe,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, other: to power the activated sludge trea...",NaN,NaN,24/06/2020 05:28:18 AM
95694,CDP Cities 2018,2018,31113,City of Yokohama,Japan,East Asia,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
95756,CDP Cities 2018,2018,16581,City of Seattle,United States of America,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
96068,CDP Cities 2018,2018,14088,City of Oslo,Norway,Europe,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
97381,CDP Cities 2018,2018,31169,Government of Hong Kong Special Administrative...,"China, Hong Kong Special Administrative Region",East Asia,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
106568,CDP Cities 2018,2018,1499,Ajuntament de Barcelona,Spain,Europe,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
121678,CDP Cities 2018,2018,3417,New York City,United States of America,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, other: electricity, thermal energy, biogas",NaN,NaN,24/06/2020 05:28:18 AM
122762,CDP Cities 2018,2018,1184,City of Austin,United States of America,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
139823,CDP Cities 2018,2018,35863,eThekwini Municipality,South Africa,Africa,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,NaN,NaN,NaN,24/06/2020 05:28:18 AM
140714,CDP Cities 2018,2018,43932,Auckland Council,New Zealand,Southeast Asia and Oceania,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
159401,CDP Cities 2018,2018,3429,City of Stockholm,Sweden,Europe,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, both vehicle fuel and electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
162055,CDP Cities 2018,2018,31156,Municipality of Curitiba,Brazil,Latin America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
171818,CDP Cities 2018,2018,14874,"City of Portland, OR",United States of America,North America,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, both vehicle fuel and electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
173668,CDP Cities 2018,2018,31111,Tokyo Metropolitan Government,Japan,East Asia,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for electricity generation",NaN,NaN,24/06/2020 05:28:18 AM
175292,CDP Cities 2018,2018,31186,Changwon City,Republic of Korea,East Asia,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,"Yes, for vehicle fuel",NaN,NaN,24/06/2020 05:28:18 AM
178102,CDP Cities 2018,2018,31179,Gemeente Rotterdam,Netherlands,Europe,Water,Wastewater,16.3a,Are you processing the captured methane for en...,0,NaN,0,NaN,Do not know,NaN,NaN,24/06/2020 05:28:18 AM

In [75]:
city_2018.loc[city_2018['Question Number'].str.startswith('Respo')].shape

(488, 18)

In [76]:
city_2018.loc[city_2018['Question Number'].str.startswith('Respo')].shape

(488, 18)

In [307]:
len(city_2018['Country'].unique())

80